name: CI

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  lint-frontend-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: rm -rf node_modules pnpm-lock.yaml
        working-directory: eveonline-helper
      - run: pnpm install
        working-directory: eveonline-helper
      - run: pnpm lint
        working-directory: eveonline-helper

  lint-frontend-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: Remove-Item -Recurse -Force node_modules, pnpm-lock.yaml
        working-directory: eveonline-helper
      - run: pnpm install
        working-directory: eveonline-helper
      - run: pnpm lint
        working-directory: eveonline-helper

  test-frontend-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
        working-directory: eveonline-helper
      - run: pnpm test -- --coverage
        working-directory: eveonline-helper
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          flags: frontend

  test-frontend-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
        working-directory: eveonline-helper
      - run: pnpm test -- --coverage
        working-directory: eveonline-helper
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          flags: frontend

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
        working-directory: eveonline-helper
      - run: pnpm build
        working-directory: eveonline-helper
      - name: Build Tauri app (Rust backend)
        run: cargo build --release
        working-directory: eveonline-helper/src-tauri

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
        working-directory: eveonline-helper
      - run: pnpm build
        working-directory: eveonline-helper
      - name: Build Tauri app (Rust backend)
        run: cargo build --release
        working-directory: eveonline-helper/src-tauri 