name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        rust: [1.80.0]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install JS dependencies
        run: npm install
      - name: Lint JS/TS
        run: npm run lint
      - name: Run JS/TS tests
        run: npm run test
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Install Rust tools
        run: |
          rustup component add clippy rustfmt
          cargo install cargo-watch
      - name: Lint Rust
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Format Rust
        run: cargo fmt --all -- --check
      - name: Build Rust
        run: cargo build --release
      - name: Run Rust tests
        run: cargo test --all 